# @package _group_
name: metaworld-mt1
num_envs: 1
benchmark:
  _target_: metaworld.MT1
  env_name: reach-v2
should_perform_reward_normalization: false
sample_task_per_episode: true
dummy: ${env.benchmark}
description:
